server {
    listen 8080;
    server_name photo.izh20.top;

    # 访问日志
    access_log /opt/homebrew/var/log/nginx/photo.access.log;
    error_log /opt/homebrew/var/log/nginx/photo.error.log;

    # nginx-status
    location /nginx-status {
        stub_status on;
        allow 127.0.0.1;
        allow 192.168.31.0/24;
        deny all;
    }

    # 禁用上传功能
    location /api/upload {
        return 403;
    }
    location /api/upload-paste {
        return 403;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        
        # 超时设置
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
}
